### PR TITLE
update to share1.0.19

### PR DESCRIPTION
**Pull request by mvertens**
These changes are needed for the upcoming noresm2_5_alpha04 tag.
This share code in numerous noresm2.5 production simulations and in all the regression testing carried out for cam, blom and cism as part of the creatino of noresm2_5_alpha04.

### CODE REVIEW

**Comment by mvertens** [comment]
@mvdebolskiy - I've been using this share code in all my simulations and in all the regression testing I've carried out.

**Comment by mvdebolskiy** [comment]
Cool. I'll merge it and then fix the other externals for standalone CTSM.

**Comment by mvdebolskiy** [comment]
@mvertens can you make a tag for this?

**Comment by mvertens** [comment]
@mvdebolskiy - I'll make a tag. Thanks!

**Pull request merged**
